feat(Tus-1254): Add client remote interfaces
Yangsta911/zhonghonghvac-go pull request #4
Opened 2024-06-20 11:21 UTC by Yangsta911

2024-06-20 11:25 UTC, qs-wang requested changes

2024-06-20 11:25 UTC, qs-wang commented on pkg/zhonghong_protocol/rtuclient.go
>  type ChecksumStruct struct{}
no need of a struct

2024-06-20 11:25 UTC, qs-wang commented on pkg/zhonghong_protocol/rtuclient.go
>  //	CRC             : 2 byte
fix the comment

2024-06-20 11:25 UTC, qs-wang commented on pkg/zhonghong_protocol/rtuclient.go
> +	if pdu.CommandType == "remote" {
split the remote control to a separate package

2024-06-20 12:50 UTC, qs-wang requested changes

2024-06-20 12:50 UTC, qs-wang commented on pkg/zhonghong_by_wire_protocol/rtuclient_by_wire.go
> +func Checksum(data []byte) int {
this is a share function

2024-06-21 08:23 UTC, ajaxjiang96 commented
I have some suggestions on naming and folder organization

1. Instead of calling them "gateway" and "by_wire" we can just refer them by their models, where "gateway" is B19 and "by_wire" is b27. It's a bit confusing because both of them are connected by wires and are called gateway.
2. Folder names should be the same as the package names
3. Packages should be separated into different folders
4. For those packages you don't want to share with third parties, you may move them into a "internal" folder. By convention other developers won't (not supposed to) quote those packages. Hopefully.
5. No empty files

2024-06-21 08:35 UTC, ajaxjiang96 commented
Meanwhile package names should be precise and short. You already have the name"zhonghong" in your library name (repo name), you may omit the "zhonghong" in the package names.
The official document encourages to use abbreviations as well. [Link here](https://go.dev/blog/package-names)

2024-06-23 10:17 UTC, qs-wang approved these changes

2024-06-23 10:18 UTC, merged